language: python
python:
  - '2.7'
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codeclimate-test-reporter
script:
  - py.test -v --cov=tina tests/
after_success:
  - codeclimate-test-reporter
notifications:
  slack:
    secure: QwhzNENXMq+OcYeI7bgEXAjz1ia0OnJ6rI5VWohxxKQRWJ1t1KVEI+OJYhNZHAlwHRnmyrjca74kt2N5RH86r/DZMtyHIcs97ciVbM1fryaTCW+PmO5KVNNyjBwNunk76ABb9UkiJInBorQQhCQz6sWLLG4UrGuk5020r2ARZixe7+q8cjntyQpfgpQJIq4IuGpKETc6dctXlG9zpopm6NzOjSF/XUX/a6fFzTw+C+sZrVD8DvoCgzmvuXm/9i67gWbDa9T+RW1CdaBIB6ANvl9Lg/9CM6KVBp3UQSiuOyNia63tbdN5y/20iuAQcNJTL06bQUEeNZAOTnM/QFNMrJjppH+vhnuvnmrpfvwZ1orXaOaYw7d+vHBvtzbZkqWetzm4o626Gm+hVjpq6ir5gVM7NZPMaiCySs5bGfcZwESvB/gYl8qo/ss02bx9+189dUS2y6r2pMS7rfQFMgPJCJfV8UWsgyiOl3Y0Yawh31qYXwk1l2Z6EgIlMNIM31L4fVsRhcxzi/WhAslUweDFE+A5CmBTPQMnZyyfGgU1GXIr3VXwGOO53rKtsLS5Bcdxh7ekjHLOaOV0XI8yK5QQbISfSg0IJkW7Y2OkfEdpd9K+rt/Zu3jF6ZQvMsJyqRb2U5a8Zo5wQ11mEqQ4+pVketPy8YfeFwjD+x9/QEN3KYw=
